sudo: true
language: go
go:
- 1.7.3
- 1.8.1
services:
- docker
- docker-compose
before_install:
- go get github.com/Masterminds/glide
- go get github.com/smartystreets/goconvey/convey
- curl -LO https://github.com/go-swagger/go-swagger/releases/download/0.10.0/swagger_linux_amd64
- chmod +x swagger_linux_amd64 && sudo mv swagger_linux_amd64 /usr/bin/swagger
- if [ ! -d $SNAP_CLIENT_GO_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdi-x; ln -s $TRAVIS_BUILD_DIR $SNAP_CLIENT_GO_SOURCE; fi # CI for forks not from intelsdi-x
env:
  global:
  - SNAP_CLIENT_GO_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/snap-client-go
  - GLIDE_HOME="${HOME}/.glide"
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=medium
install:
- export TMPDIR=$HOME/tmp
- mkdir -p $TMPDIR
- cd $SNAP_CLIENT_GO_SOURCE # change dir into source
- make
script:
- make test 2>&1 # Run test suite
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=